-- 30 P0 catalog rows. code is stable (11-catalog-seed.md).
-- tags: free_weight for BARBELL/DUMBBELL/KETTLEBELL.

INSERT INTO exercise_catalog (id, code, name, muscle_group, equipment, pattern, swap_group, tags, is_stretch) VALUES
(1001, 'bb_back_squat', '杠铃深蹲', 'QUAD', 'BARBELL', 'SQUAT', 'squat_quad', '["free_weight"]', FALSE),
(1002, 'goblet_squat', '高脚杯深蹲', 'QUAD', 'DUMBBELL', 'SQUAT', 'squat_quad', '["free_weight"]', FALSE),
(1003, 'smith_squat', '史密斯深蹲', 'QUAD', 'SMITH', 'SQUAT', 'squat_quad', '[]', FALSE),
(1004, 'leg_press_45', '45度腿举', 'QUAD', 'LEG_PRESS', 'SQUAT', 'squat_quad', '[]', FALSE),
(1005, 'walking_lunge', '步行弓步', 'QUAD', 'DUMBBELL', 'LUNGE', 'lunge_quad', '["free_weight"]', FALSE),
(1006, 'rd_deadlift', '罗马尼亚硬拉', 'HAMSTRING', 'BARBELL', 'HINGE', 'hinge_post', '["free_weight"]', FALSE),
(1007, 'db_rdl', '哑铃RDL', 'HAMSTRING', 'DUMBBELL', 'HINGE', 'hinge_post', '["free_weight"]', FALSE),
(1008, 'hip_thrust', '臀桥/髋推', 'GLUTE', 'BARBELL', 'HINGE', 'hinge_post', '["free_weight"]', FALSE),
(1009, 'lying_leg_curl', '俯卧腿弯举', 'HAMSTRING', 'MACHINE', 'ISOLATION', 'ham_iso', '[]', FALSE),
(1010, 'leg_extension', '腿屈伸', 'QUAD', 'MACHINE', 'ISOLATION', 'quad_iso', '[]', FALSE),
(1011, 'bb_bench', '杠铃卧推', 'CHEST', 'BARBELL', 'HORIZONTAL_PUSH', 'hpush_chest', '["free_weight"]', FALSE),
(1012, 'db_bench', '哑铃卧推', 'CHEST', 'DUMBBELL', 'HORIZONTAL_PUSH', 'hpush_chest', '["free_weight"]', FALSE),
(1013, 'push_up', '俯卧撑', 'CHEST', 'BODYWEIGHT', 'HORIZONTAL_PUSH', 'hpush_chest', '[]', FALSE),
(1014, 'machine_chest_press', '器械胸推', 'CHEST', 'MACHINE', 'HORIZONTAL_PUSH', 'hpush_chest', '[]', FALSE),
(1015, 'ohp_bb', '杠铃肩上推', 'SHOULDER', 'BARBELL', 'VERTICAL_PUSH', 'vpush_shoulder', '["free_weight"]', FALSE),
(1016, 'ohp_db', '哑铃肩推', 'SHOULDER', 'DUMBBELL', 'VERTICAL_PUSH', 'vpush_shoulder', '["free_weight"]', FALSE),
(1017, 'lateral_raise', '侧平举', 'SHOULDER', 'DUMBBELL', 'ISOLATION', 'shoulder_iso', '["free_weight"]', FALSE),
(1018, 'pull_up', '引体向上', 'BACK', 'PULLUP_BAR', 'VERTICAL_PULL', 'vpull_back', '[]', FALSE),
(1019, 'lat_pulldown', '高位下拉', 'BACK', 'CABLE', 'VERTICAL_PULL', 'vpull_back', '[]', FALSE),
(1020, 'bb_row', '杠铃划船', 'BACK', 'BARBELL', 'HORIZONTAL_PULL', 'hpull_back', '["free_weight"]', FALSE),
(1021, 'seated_cable_row', '坐姿划船', 'BACK', 'CABLE', 'HORIZONTAL_PULL', 'hpull_back', '[]', FALSE),
(1022, 'db_row', '单臂哑铃划船', 'BACK', 'DUMBBELL', 'HORIZONTAL_PULL', 'hpull_back', '["free_weight"]', FALSE),
(1023, 'bb_curl', '杠铃弯举', 'BICEP', 'BARBELL', 'ISOLATION', 'biso', '["free_weight"]', FALSE),
(1024, 'db_curl', '哑铃弯举', 'BICEP', 'DUMBBELL', 'ISOLATION', 'biso', '["free_weight"]', FALSE),
(1025, 'tricep_pushdown', '绳索下压', 'TRICEP', 'CABLE', 'ISOLATION', 'tiso', '[]', FALSE),
(1026, 'plank', '平板支撑', 'CORE', 'BODYWEIGHT', 'CORE', 'core', '[]', FALSE),
(1027, 'cable_crunch', '绳索卷腹', 'CORE', 'CABLE', 'CORE', 'core', '[]', FALSE),
(1028, 'calf_raise', '提踵', 'CALF', 'MACHINE', 'ISOLATION', 'calf', '[]', FALSE),
(1029, 'farmer_carry', '农夫行走', 'CORE', 'DUMBBELL', 'CARRY', 'carry', '["free_weight"]', FALSE),
(1030, 'face_pull', '面拉', 'SHOULDER', 'CABLE', 'ISOLATION', 'shoulder_iso', '[]', FALSE);
